site:
  name: Home Free Stairs
  site: 'https://deploy-preview-23--home-free-stairs-oc.netlify.app/'
  base: '/'
  trailingSlash: false

metadata:
  title:
    default: Home Free Stairs
    template: '%s'
  description: 'Expert stairlift services designed around your home and your needs.'
  openGraph:
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: default
  clientRouter: false
