site:
  name: Home Free Stairs
  site: 'https://example.com'
  base: '/'
  trailingSlash: false

metadata:
  title:
    default: Home Free Stairs
    template: '%s'
  description: ''

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'light'
