site:
  name: Home Free Stairs
  site: 'https://example.com'
  base: '/'
  trailingSlash: false

metadata:
  title:
    default: Home Free Stairs
    template: '%s'
  description: ''
  openGraph:
  images:
    - url: 'https://example.com/assets/images/default.png'
      width: 1200
      height: 628

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: default
  clientRouter: false
